### PR TITLE
update for MathJax v2.5 release

### PR DESCRIPTION
**Pull request by pkra**

### CODE REVIEW

**Comment by jgable** [comment]
You should merge this, it fixes the grunt undefined error (#3) because `grunt.registerTask('mjNode', [` is after the closing brace.

**Comment by pkra** [comment]
Meh, dropped off the radar -- thanks for poking, @jgable. 

@dpvc any objection?

**Comment by dpvc** [comment]
@pkra, this is your code, so I'd say it is your call.  I don't see anything problematic, but I haven't tried it out, either.

**Comment by pkra** [comment]
@dpvc thx. @jgable thanks again for poking and also for your comment re #3

**Pull request merged**
